### ISSUE TITLE
tabView v2.0.6 下拉刷新

### ISSUE THREAD

**Issue by 294585820** [zyslife/react-native-head-tab-view#52]
1.更新了最新版本
2.使用下拉onStartRefresh 
当我下拉刷新时感觉会顿卡 iPhone 6P

**Comment by zyslife** [comment]
是标签页的下拉刷新还是Tabview的下拉刷新呢？

**Comment by 294585820** [comment]
Tabview V2.0.6 下拉刷新

**Comment by zyslife** [comment]
> Tabview V2.0.6 下拉刷新

Example会卡吗？能提供最小能复现的代码吗？

**Comment by 294585820** [comment]
很抱歉现在才回复
1.用tabView 下拉，Example也是不流畅的有点卡顿，如果你多点数据卡顿就很明显，
2.用标签页下拉，不会出现卡顿的问题

**Comment by zyslife** [comment]
> 很抱歉现在才回复
> 
> 1.用tabView 下拉，Example也是不流畅的有点卡顿，如果你多点数据卡顿就很明显，
> 
> 2.用标签页下拉，不会出现卡顿的问题

下拉刷新还处于实验中，尽量不要使用，我下个版本尽力优化

**Comment by zyestin** [comment]
> > 很抱歉现在才回复
> > 1.用tabView 下拉，Example也是不流畅的有点卡顿，如果你多点数据卡顿就很明显，
> > 2.用标签页下拉，不会出现卡顿的问题
> 
> 下拉刷新还处于实验中，尽量不要使用，我下个版本尽力优化

加油加油，等待ing

**Comment by zyslife** [comment]
After v3.0, the built-in tabs component is not supported.We will only extend the other tabs component so that each Tab page has a shared collapsible header.

The following components are currently supported:
react-native-scrollable-tab-view
react-native-tab-view

For detailed usage, please refer to Example and Installation.

@zyestin  下拉刷新有优化一部分，后面还会持续优化这块，你可以先体验下

**Comment by 294585820** [comment]
我测试了一下性能是提高了很多，但是下拉放手瞬间页面收起来时，加载图标会出现图广告图上

**Comment by zyslife** [comment]
> 我测试了一下性能是提高了很多，但是下拉放手瞬间页面收起来时，加载图标会出现图广告图上

现在加载图标是会出现在广告图上，这是做出的部分牺牲，下个版本我会修复这个问题，并且再一步提升性能。

**Comment by zyslife** [comment]
> CollapsibleHeaderTabView, SlideTabView 这两个有什么区别，
> 
> 用SlideTabView不会出现这样的问题 （加载图标是会出现在广告图上）



> CollapsibleHeaderTabView, SlideTabView 这两个有什么区别，
> 
> 用SlideTabView不会出现这样的问题 （加载图标是会出现在广告图上）

这个滑动的时候相当于将整个tabview位移了，向上滑动到tabbar的位置会自动停下来。

**Comment by 294585820** [comment]
好的谢谢，暂时先用SlideTabView
