### ISSUE TITLE
renderScene is called multiple times every time a change tabs

### ISSUE THREAD

**Issue by andrewerrico** [zyslife/react-native-head-tab-view#56]
With every tab change, `renderScene` gets called multiple times, and sometimes the index will be reset to 0 which causes the first scene to render rather than the tab I selected. Any ideas?

**Comment by zyslife** [comment]
Thank you for raising these issues, yes, these issues exist and I will fix them in the next release.

**Comment by zyslife** [comment]
After v3.0, the built-in tabs component is not supported.We will only extend the other tabs component so that each Tab page has a shared collapsible header.

The following components are currently supported:
react-native-scrollable-tab-view
react-native-tab-view

For detailed usage, please refer to Example and Installation.  @andrewerrico

**Comment by zyslife** [comment]
It's been too long. I'm going to turn off this issue. If you have any problems, please open it again.
